name: Drive to YouTube Upload

on:
  schedule:
    - cron: '0 */12 * * *'  # runs every 12 hours
  workflow_dispatch:        # allows manual trigger

jobs:
  upload:
    runs-on: ubuntu-latest
    timeout-minutes: 360

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install google-api-python-client google-auth google-auth-oauthlib google-auth-httplib2

      - name: Restore credential files
        shell: bash
        run: |
          printf '%s' "${{ secrets.CLIENT_SECRET_JSON }}" > client_secret.json
          printf '%s' "${{ secrets.TOKEN_JSON }}" > token.json

      - name: Run upload script
        run: python main.py
